<?php
/**
 * Sezzlepay
 *
 * @category   design
 * @package    base_default
 * @author     Sezzle Team
 */
?>
<?php
$mwOneStepCheckout = Mage::helper('core')->isModuleEnabled("MW_Onestepcheckout");
?>
<?php if( $mwOneStepCheckout ): ?>
	<script src="<?php echo $this->getJsUrl('sezzle/checkout/mageworld_onestep.js') ?> "></script>
<?php else: ?>
	<script src="<?php echo $this->getJsUrl('sezzle/checkout/onepage.js') ?> "></script>
<?php endif; ?>