<div style="text-align:center">
    <h2>We are redirecting you to payment. Please wait ...</h2>
    <br>
    <img src="http://i.imgur.com/KUJoe.gif" />
</div>

<!-- Hidden form to submit -->
<form name="sezzle" method="post" action="<?php echo $url; ?>">
    <?php
        foreach($data as $key => $value) {
            $encode_value = htmlspecialchars($value, ENT_QUOTES | ENT_HTML401);
            $encode_key = htmlspecialchars($key, ENT_QUOTES | ENT_HTML401);
            echo "<input type='hidden' name='$encode_key' value='$encode_value'>";
        }
    ?>
</form>
<script type="text/javascript">
document.sezzle.submit();
</script>